version: '3.7'
services:
  metabase-reverse:
    # image: metabase/metabase-enterprise:v1.37.8
    image: metabase/metabase:v0.37.8
    container_name: metabase-reverse
    hostname: metabase-reverse
    volumes: 
    - /dev/urandom:/dev/random:ro
    #ports:
    #  - 3000:3000
    networks: 
      - metanet-private
  haproxy:
    image: haproxy:2.3.4-alpine
    hostname: haproxy
    container_name: haproxy
    volumes: 
      - $PWD/config/:/usr/local/etc/haproxy/:ro
      - $PWD/log:/dev/log
    networks:
      - metanet-private
      - metanet-public
    ports:
      - 8080:80
    depends_on: 
      - metabase-reverse
networks: 
  metanet-private:
    driver: bridge
  metanet-public:
    driver: bridge